### ISSUE TITLE
Brightness changes to 100%

### ISSUE THREAD

**Issue by hunterqwertz** [jstrausd/homebridge-simple-wled#25]
Hello!
I currently have the problem that every time I change the brightness in the Home App, it changes to 100% and only comes to the set value after a few seconds.
This has only been the case since iOS 15, on macOS the error almost never occurs.
Edit: Checked with an iOS 14 Device, problem does not appear there

**Comment by Bene2103** [comment]
Hi, this behavior is because the set value of your action isn't cached. 
You set the desired value -> HomeKit tells WLED to go to xx% -> 4.5sek simple-wled updates the values from device -> HomeKit shows correct value.

In my opinion its not a bug its more of a "not nice" but not a problem actually.

**Comment by AlexKusnezov** [comment]
Hey, also the light won’t update in the HomeKit app when changing in another app e.g. Alexa or WLED app

**Comment by jstrausd** [comment]
I just released version 1.3.1 with some bug fixes.

It fixes the issue that the brightness changes shortly to 100% after changing the brigthness
It fixes the error described in Issue #32 (Error while polling WLED)
And some small changes in package.json (dependencies)
