### ISSUE TITLE
unable to add to HomeKit

### ISSUE THREAD

**Issue by lastrebel** [jstrausd/homebridge-simple-wled#49]
Hello, this happens again (#26), unable to add any WLED device manually to Home app on iOS16.(following exact steps from @jstrausd, I have done it in past successfully). Both lights were connected and used from Home iOS app for cca 1.5 years, last week they stopped, had to reset them to factory settings and since than 2 problems which were not there before.

1# (#26 ) unable to add them to Home app, in Homebridge they show, maybe it remembers their Mac address or osme other identifier since I had to remove them from HHomekit when they stopped to work. 

2# (#36 ) weird I started to have problem with brightness, this is the strangest part because for 1.5 years I never had this problem and was always conntroling lights from iOS Home app, and after reset to factory settings they start to show this issue.

Hope this great plugin is not already dead.

**Comment by jstrausd** [comment]
Hello, 

For the first problem try to rename your WLED Devices in the Homebridge-Config, then restart the Homebridge and try connecting it to the HomeKit App.

For the second problem, I am really looking to spend more time in this project and fix this bug, because right now i had really less time for further development on this plugin.

**Comment by lastrebel** [comment]
Thank you, renaming in config file helped. Second issue is in separate issue #36 therfore I will close this one.
